# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.6 environment
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      
      #redis setup
      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '6.x'
          auto-start: "true"  
      #test redis
      - name: redis test
        run: redis-cli ping
          
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run our unit tests
      - name: Run unit tests
        run: python test_application.py
        env:
          redis_host: '127.0.0.1'
          redis_port: '6379'
          landing_url: 'localhost'
